### ISSUE TITLE
运行yuque-hexo sync会报错

### ISSUE THREAD

**Issue by a506488043** [x-cold/yuque-hexo#15]
async run(){
        ^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at MainCommand.add (/usr/local/lib/node_modules/yuque-hexo/node_modules/common-bin/lib/command.js:105:16)

![image](https://user-images.githubusercontent.com/16434125/49736754-ed9c4b00-fcc5-11e8-9d6c-2c11fbe4b4a9.png)

**Comment by x-cold** [comment]
请升级 node 版本至 v8.x，建议使用 nvm 等工具进行 node.js 的版本控制

**Comment by a506488043** [comment]
哪这个呢？
![image](https://user-images.githubusercontent.com/16434125/49776283-4e636c00-fd36-11e8-97e3-f4282e677e40.png)
同步后没yuque.json
package.json配置
`{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "scripts": {
    "clean": "hexo clean",
    "clean:yuque": "DEBUG=yuque-hexo.* yuque-hexo clean",
    "deploy": "hexo deploy",
    "publish": "npm run clean && npm run deploy",
    "dev": "hexo s",
    "sync": "DEBUG=yuque-hexo.* yuque-hexo sync",
    "reset": "npm run clean:yuque && npm run sync"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.1"
  },
  "yuqueConfig": {
    "baseUrl": "https://www.yuque.com/api/v2",
    "login": "bte3tg",
    "repo": "gv3eii"
  },
  "devDependencies": {
    "yuque-hexo": "^1.3.0"
  }
}
`

**Comment by x-cold** [comment]
这个是最新的 yuque-hexo 吗，使用 'npm i -g yuque-hexo@latest' 更新下试试。
或者提供一下最下可复现的仓库

**Comment by a506488043** [comment]
@x-cold 是因为语雀的知识库不是公开的，执行命令行后会报错。

还有语雀上的图片不能同步到hexo上吗？！

我的文章有一个图片加载不出来。
