### ISSUE TITLE
同步之后生成了重复的front-matter

### ISSUE THREAD

**Issue by iszengmh** [x-cold/yuque-hexo#27]
不知道怎么回事，之前好好的。
![image](https://user-images.githubusercontent.com/16217979/57190485-3d1d3500-6f4d-11e9-977b-4875364c6641.png)

![image](https://user-images.githubusercontent.com/16217979/57190474-270f7480-6f4d-11e9-8591-1f312aa968f3.png)
![image](https://user-images.githubusercontent.com/16217979/57190499-6211a800-6f4d-11e9-8264-e40e07be2538.png)

```

git.checkout
1.20s$ git clone --depth=50 --branch=blog https://github.com/iszengmh/iszengmh.github.io.git iszengmh/iszengmh.github.io
Cloning into 'iszengmh/iszengmh.github.io'...
remote: Enumerating objects: 6822, done.
remote: Counting objects: 100% (6822/6822), done.
remote: Compressing objects: 100% (1849/1849), done.
remote: Total 6822 (delta 2914), reused 6679 (delta 2784), pack-reused 0
Receiving objects: 100% (6822/6822), 6.13 MiB | 24.04 MiB/s, done.
Resolving deltas: 100% (2914/2914), done.
$ cd iszengmh/iszengmh.github.io
$ git checkout -qf c3cffe6728a7047f3ec7898b92f2744502dfab88
Setting environment variables from repository settings
$ export GH_TOKEN=c0d9c230ed578cfdccc2f39868ef9e83bdd90024
Setting environment variables from .travis.yml
$ export GH_REF=github.com/iszengmh/iszengmh.github.io.git
nvm.install
3.11s$ nvm install 10.15.0
Downloading and installing node v10.15.0...
Downloading https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x64.tar.xz...
Computing checksum with sha256sum
Checksums matched!
Now using node v10.15.0 (npm v6.4.1)
cache.1
Setting up build cache
$ export CASHER_DIR=${TRAVIS_HOME}/.casher
0.15s$ Installing caching utilities
0.00s1.32sattempting to download cache archive
fetching blog/cache-linux-trusty-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855--node-10.15.0.tgz
found cache
0.00s2.45sadding /home/travis/build/iszengmh/iszengmh.github.io/node_modules to cache
creating directory /home/travis/build/iszengmh/iszengmh.github.io/node_modules
$ node --version
v10.15.0
$ npm --version
6.4.1
$ nvm --version
0.34.0
before_install
7.65s$ npm install -g hexo-cli
/home/travis/.nvm/versions/node/v10.15.0/bin/hexo -> /home/travis/.nvm/versions/node/v10.15.0/lib/node_modules/hexo-cli/bin/hexo
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/hexo-cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
+ hexo-cli@1.1.0
added 225 packages from 434 contributors in 7.203s
install.1
3.78s$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
audited 5844 packages in 3.336s
found 7 vulnerabilities (5 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
install.2
4.48s$ npm install hexo-deployer-git --save
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
+ hexo-deployer-git@0.2.0
updated 1 package and audited 5844 packages in 4.039s
found 7 vulnerabilities (5 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
install.3
6.74s$ npm i -g yuque-hexo
/home/travis/.nvm/versions/node/v10.15.0/bin/yuque-hexo -> /home/travis/.nvm/versions/node/v10.15.0/lib/node_modules/yuque-hexo/bin/yuque-hexo.js
+ yuque-hexo@1.5.0
added 211 packages from 166 contributors in 6.304s
0.37s$ yuque-hexo clean
[INFO] remove yuque posts: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque
[INFO] remove yuque local cache: /home/travis/build/iszengmh/iszengmh.github.io/yuque.json
[INFO] yuque-hexo clean done!
The command "yuque-hexo clean" exited with 0.
10.21s$ yuque-hexo sync
[INFO] clear previous directory.
[INFO] remove yuque posts: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque
[INFO] reading from local file: /home/travis/build/iszengmh/iszengmh.github.io/yuque.json
[INFO] article amount: 21
[INFO] download article body: java之如何使当前程序使用代理
[INFO] download article body: js之IE浏览器下打开F12，js才能正常运行
[INFO] download article body: java之各种日期格式
[INFO] download article body: oracle之记录被另一个用户锁住
[INFO] download article body: 工具之tcping
[INFO] download article body: oracle之索引
[INFO] download article body: 定时任务之cron表达式
[INFO] download article body: spring boot之配置数据源时提示无法加载驱动类
[INFO] download article body: maven之安装第三方jar到本地 出现 The goal you specified requires a project to execute but there is no POM in this directory 错误
[INFO] download article body: mysql之Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver
[INFO] download article body: maven之如何引入oracle依赖
[INFO] download article body: oracle之ORA-27102: out of memory或者O/S-Error: (OS 1455) 页面文件太小，无法完成操作。
[INFO] download article body: oracle之重装系统后恢复
[INFO] download article body: svn之svn server重装系统恢复
[INFO] download article body: spring之spring boot
[INFO] download article body: oracle之技术经验
[INFO] download article body: eclipse之配置hibernate逆向生成映射文件和实体类
[INFO] download article body: webhook_test
[INFO] download article body: mysql之绿色版
[INFO] download article body: 语雀之语雀+serverless+travis CI+hexo+github搭建云写作博客
[INFO] download article body: 语雀之Hello World
[INFO] download articls done!
[INFO] writing to local file: /home/travis/build/iszengmh/iszengmh.github.io/yuque.json
[INFO] create posts director (if it not exists): /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/java之如何使当前程序使用代理.md
[ERROR] invalid post: [object Object]
[ERROR] invalid post: [object Object]
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/oracle之记录被另一个用户锁住.md
[ERROR] invalid post: [object Object]
[ERROR] invalid post: [object Object]
[ERROR] invalid post: [object Object]
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/spring boot之配置数据源时提示无法加载驱动类.md
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/maven之安装第三方jar到本地 出现 The goal you specified requires a project to execute but there is no POM in this directory 错误.md
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/mysql之Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver.md
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/maven之如何引入oracle依赖.md
[ERROR] invalid post: [object Object]
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/oracle之重装系统后恢复.md
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/svn之svn server重装系统恢复.md
[ERROR] invalid post: [object Object]
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/oracle之技术经验.md
[ERROR] invalid post: [object Object]
[ERROR] invalid post: [object Object]
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/mysql之绿色版.md
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/语雀之语雀+serverless+travis CI+hexo+github搭建云写作博客.md
[INFO] generate post file: /home/travis/build/iszengmh/iszengmh.github.io/source/_posts/yuque/语雀之Hello World.md
[INFO] yuque-hexo sync done!
The command "yuque-hexo sync" exited with 0.
0.84s$ hexo clean
(node:5212) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Deleted database.
INFO  Deleted public folder.
The command "hexo clean" exited with 0.
7.65s$ hexo generate
(node:5228) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
ERROR Process failed: _posts/yuque/java之如何使当前程序使用代理.md
YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 6, column 18:
    description: tags: [java, 代理]categories: java参考链接 ... 
                     ^
    at generateError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1027:9)
    at composeNode (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at parseYAML (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo/lib/plugins/processor/post.js:51:20)
    at tryCatcher (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:638:18)
ERROR Process failed: _posts/yuque/maven之如何引入oracle依赖.md
YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 6, column 18:
    description: tags: [maven,oracle]categories: mave ... 
                     ^
    at generateError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1027:9)
    at composeNode (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at parseYAML (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo/lib/plugins/processor/post.js:51:20)
    at tryCatcher (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:638:18)
ERROR Process failed: _posts/yuque/maven之安装第三方jar到本地 出现 The goal you specified requires a project to execute but there is no POM in this directory 错误.md
YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 6, column 18:
    description: tags: [maven,oracle]categories: mave ... 
                     ^
    at generateError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1027:9)
    at composeNode (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at parseYAML (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo/lib/plugins/processor/post.js:51:20)
    at tryCatcher (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:638:18)
ERROR Process failed: _posts/yuque/mysql之绿色版.md
YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 6, column 18:
    description: tags: [mysql,数据库]categories: mysql参考 ... 
                     ^
    at generateError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1027:9)
    at composeNode (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at parseYAML (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo/lib/plugins/processor/post.js:51:20)
    at tryCatcher (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:638:18)
ERROR Process failed: _posts/yuque/oracle之记录被另一个用户锁住.md
YAMLException: incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line at line 6, column 18:
    description: tags: [oracle,数据库]categories: oracle ... 
                     ^
    at generateError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readBlockMapping (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1027:9)
    at composeNode (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1519:3)
    at loadDocuments (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1575:5)
    at Object.load (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/js-yaml/lib/js-yaml/loader.js:1596:19)
    at parseYAML (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:80:21)
    at parse (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo-front-matter/lib/front_matter.js:56:12)
    at Promise.all.spread (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/hexo/lib/plugins/processor/post.js:51:20)
    at tryCatcher (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/build/iszengmh/iszengmh.github.io/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill 
```

**Comment by x-cold** [comment]
麻烦补充一下生成的文档

**Comment by iszengmh** [comment]
markdown文件部分内容如下，好像重复生成了front-matter
```

---

title: java之如何使当前程序使用代理

description: tags:[java, 代理]categories: java参考链接java中设置网络代理——简书@jijs java之如何使当前程序使用代理概述java中支持的代理java中支持 HTTP代理、HTTPS代理、Socket代理、FTP代理 。&amp;lt;!--more--&amp;gt;程序中编写程序...

date: 2019-05-05 12:13:10 +0800

tags: []

---
tags:[java, 代理]

categories: java

---

<a name="VKpaC"></a>
# 参考链接

[java中设置网络代理——简书@jijs](https://www.jianshu.com/p/9e1abe05314d) 

<a name="9rrtR"></a>
# java之如何使当前程序使用代理
<a name="jldiB"></a>
## 概述
<a name="cSPtQ"></a>
## java中支持的代理
java中支持 HTTP代理、HTTPS代理、Socket代理、FTP代理 。
```

**Comment by heliuphy** [comment]
+1 同样的问题

**Comment by heliuphy** [comment]
我删除掉了 `hexo.js` 和 `Downloader.js` 里面的 `description` 项之后正常了，楼主可以试一下。

**Comment by iszengmh** [comment]
我是使用travi-ci自动构建，好像没办法改

**Comment by x-cold** [comment]
今晚尝试修复这个问题

**Comment by x-cold** [comment]
```

---

title: Git 实用指南

description: tags: [git]date: 2019-03-28个人整理的一些常用的 Git 概念和命令集合，方便速查和快速解决某些场景下的问题，覆盖了日常开发和协同工作下的一部分场景，不只是命令行的介绍。欢迎关注语雀原文，持续更新！精简入门1、克隆仓库克隆仓库会下载仓库完整的文件、分支和历史记录。gi...

date: 2019-03-28 00:00:00 +0800

tags: git

---
```

原来是语雀的默认的 description 里面包含了正文顶部的内容，所以包含了 tags: [] 等信息，导致 front-matter 解析错误。

**Comment by iszengmh** [comment]
大佬，牛逼

**Comment by Zricky** [comment]
![image](https://user-images.githubusercontent.com/29839337/58223512-88588580-7d4c-11e9-908a-1a15c8ace9ea.png)
同步之后的标签 
tags: travis,hexo
categories: hexo,travis
少了[ ]
调试也没找到原因 试了几个版本多标签时都不行

**Comment by Zricky** [comment]
> ![image](https://user-images.githubusercontent.com/29839337/58223512-88588580-7d4c-11e9-908a-1a15c8ace9ea.png)
> 同步之后的标签
> tags: travis,hexo
> categories: hexo,travis
> 少了[ ]
> 调试也没找到原因 试了几个版本多标签时都不行

const template = `
---
<% for (const key in props) {%>
<% if (key=='tags'||key=='categories'){%>
<%= key %>: [<%= props[key] %>]
<% } else {%>
<%= key %>: <%= props[key] %>
<% } %>
<% } %>
---
<%- raw %>
`;
修改这个即可
